package main

// DO NOT EDIT, this file is generated by hover at compile-time for the openpgp plugin.

import (
	bitmaelum "github.com/bitmaelum/bitmaelum_flutter_plugin/go"
	flutter "github.com/go-flutter-desktop/go-flutter"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&bitmaelum.Plugin{}))
}
